@startuml
left to right direction
' uncomment the line below if you're using computer with a retina display
' skinparam dpi 300
!define Table(name,desc) class name as "desc" << (T,#FFAAAA) >>
' we use bold for primary key
' green color for unique
' and underscore for not_null
!define primary_key(x) <b>x</b>
!define unique(x) <color:green>x</color>
!define not_null(x) <u>x</u>
' other tags available:
' <i></i>
' <back:COLOR></color>, where color is a color name or html color code
' (#FFAACC)
' see: http://plantuml.com/classes.html#More
hide methods
hide stereotypes

' entities

Table(User,"User \n Sử dụng obj User của Salesforce") { 
    primary_key(Id) Id
    RemainingHoliday number
    TeamId reference
} 

Table(Team,"Team\n Team table"){
    primary_key(Id) Id
    not_null(Name) String
    LeaderId reference
    not_null(IsDeleted) boolean
    not_null(CreatedById) reference
    not_null(CreatedDate) dateTime
    not_null(LastModifiedById) reference
    not_null(LastModifiedDate) dateTime
    not_null(SystemModstamp) dateTime
    
}

Table(WorkingTime,"Working Time Table"){
    primary_key(Id) Id
    primary_key(UserId) reference
    primary_key(Date) Date
    WeekDay string
    StartTime dateTime
    EndTime dateTime
    LateHours number
    HolidayHours number 
    not_null(ComfirmedByLeader) boolean
    not_null(ComfirmedByManager) boolean
    not_null(IsDeleted) boolean
    not_null(CreatedById) reference
    not_null(CreatedDate) dateTime
    not_null(LastModifiedById) reference
    not_null(LastModifiedDate) dateTime
    not_null(SystemModstamp) dateTime
}

Table(Report,"Report Table"){
    primary_key(Id) Id
    not_null(Year) number
    not_null(Month) number
    SumOfWorkingTime number
    SumOfLateHours number
    SumOfHolidayHours number
    not_null(IsDeleted) boolean
    not_null(CreatedById) reference
    not_null(CreatedDate) dateTime
    not_null(LastModifiedById) reference
    not_null(LastModifiedDate) dateTime
    not_null(SystemModstamp) dateTime
}

Table(Holiday,"Holiday Table"){
    primary_key(Date) Date
    Name string
    not_null(IsDeleted) boolean
    not_null(CreatedById) reference
    not_null(CreatedDate) dateTime
    not_null(LastModifiedById) reference
    not_null(LastModifiedDate) dateTime
    not_null(SystemModstamp) dateTime
}

' relationships

' one or many
User }|--|| Team   :"1 người chỉ thuộc 1 team, 1 team có nhiều người"
User ||--|{ WorkingTime :"1 người có nhiều bản ghi thời gian làm việc"
User ||--o{ Team  :"1 người có thể là leader nhiều team, hoặc ko team nào"

@enduml
